/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_pojler_jni_Main */

#ifndef _Included_com_pojler_jni_Main
#define _Included_com_pojler_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pojler_jni_Main
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_pojler_jni_Main_count
  (JNIEnv *, jobject, jintArray, jint);


JNIEXPORT jint JNICALL Java_com_pojler_jni_Main_add
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jintArray JNICALL Java_com_pojler_jni_Main_cummulativeSum
  (JNIEnv *, jobject, jintArray);

JNIEXPORT void JNICALL Java_com_pojler_jni_Main_sumaryOfMatrix
(JNIEnv *, jobject, jintArray, jint, jint, jint, jintArray, jintArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
