/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pojler_jni_Main */

#ifndef _Included_com_pojler_jni_Main
#define _Included_com_pojler_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pojler_jni_Main
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_pojler_jni_Main_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_pojler_jni_Main
 * Method:    count
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_pojler_jni_Main_count
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
